### ISSUE TITLE
Installation requirements and requirements.txt are different

### ISSUE THREAD

**Issue by mpvanderschelling** [bessagroup/rvesimulator#44]
## Problem

In your repository, you have a `requirements.txt` and `setup.cfg` file:
* In the `setup.cfg`; there are `install_requires` listed:

```
install_requires =
    numpy
    pandas
    matplotlib
    scipy
```

However, the requirements in `requirements.txt` are version dependent, thus different:

```
matplotlib>=3.6.2
numpy>=1.23.5
scipy>=1.9.3
pandas>=1.53
```

## Possible solution

Change your `setup.cfg` to read the requirements file as `install_requires`:

```
install_requires = file: requirements.txt
```

**Comment by JiaxiangYi96** [comment]
thank for the comments, this issue is fixed
